
name: Migrate Environments

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run script
      env:
        GH_PAT_SOURCE: ${{ secrets.GH_PAT_SOURCE }}
        GH_PAT_TARGET: ${{ secrets.GH_PAT_TARGET }}
      run: node migrate.js
