name: Migrate environments

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment environments from source repo
        id: get-envs
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.getAllEnvironments({
              owner: 'liatrio-enterprise',
              repo: 'environment-migration-test',
            });
            console.log(response.data);

            for (const env of response.data.environments) {
              console.log(env.name);
              console.log(env.protection_rules);
              console.log(env.deployment_branch_policy);
            }

            return response.data;
      
      - name: Create PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            console.log(JSON.stringify(${{ steps.get-envs.outputs.result }}));

            const response = ${{ steps.get-envs.outputs.result }};

            for (const env of response.environments) {
              // console.log(env.name);
              // console.log(env.protection_rules);
              // console.log(env.deployment_branch_policy);

              if (env.deployment_branch_policy === null){
                github.rest.repos.createOrUpdateEnvironment({
                  owner: 'liatrio-enterprise',
                  repo: 'calvin-test',
                  environment_name: env.name,
                  deployment_branch_policy: null
                })
              } else {
                github.rest.repos.createOrUpdateEnvironment({
                  owner: 'liatrio-enterprise',
                  repo: 'calvin-test',
                  environment_name: env.name,
                  deployment_branch_policy: {
                    protected_branches: env.deployment_branch_policy.protected_branches,
                    custom_branch_policies: env.deployment_branch_policy.custom_branch_policies,
                  }
                })
              }
            }

      - name: Migrate environment secrets
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const response = ${{ steps.get-envs.outputs.result }};
      
            for (const env of response.environments) {
              //const secretsResponse = await github.rest.actions.listEnvironmentSecrets({
              //  owner: 'liatrio-enterprise',
              //  repo: 'environment-migration-test',
              //  environment_name: env.name,
              //});

              const secretsResponse = await github.rest.actions.listEnvironmentSecrets({
                repository_id: 'environment-migration-test',
                environment_name: env.name
              });

              console.log(JSON.stringify(secretResponse));
              // console.log(secretResponse)
      
              //for (const secret of secretsResponse.data.secrets) {
                // Get the value of the secret
                //const secretValue = await github.rest.actions.getRepoSecret({
                //  owner: 'liatrio-enterprise',
                //  repo: 'environment-migration-test',
                //  secret_name: secret.name,
                //});
      
                // Migrate the secret to the target repository
                //await github.rest.actions.createOrUpdateEnvironmentSecret({
                //  owner: 'liatrio-enterprise',
                //  repo: 'calvin-test',
                //  environment_name: env.name,
                //  secret_name: secret.name,
                  // encrypted_value: secretValue.data.encrypted_value,
                  // key_id: secretValue.data.key_id,
                //});
              //}
            }       
