name: Migrate environments

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment environments from source repo
        id: get-envs
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.getAllEnvironments({
              owner: 'liatrio-enterprise',
              repo: 'environment-migration-test',
            });
            console.log(response.data);

            for (const env of response.data.environments) {
              console.log(env.name);
              console.log(env.protection_rules);
              console.log(env.deployment_branch_policy);
            }

            return response.data;
      
      - name: Create
        uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(${{ steps.get-envs.outputs.result }}));

            const response = ${{ steps.get-envs.outputs.result }};

            for (const env of response.data.environments) {
              console.log(env.name);
              console.log(env.protection_rules);
              console.log(env.deployment_branch_policy);
            }
          
